#!/bin/bash
#SBATCH --job-name=dadi_dfe_inference_snm_equil
#SBATCH --output=outfiles/dadi_snm_equil_3/%x-%A_%a.out
#SBATCH --error=outfiles/dadi_snm_equil_3/%x-%A_%a.err
#SBATCH --account=rgutenk
#SBATCH --partition=high_priority
#SBATCH --qos=user_qos_rgutenk
#SBATCH --mail-type=ALL
#SBATCH --mail-user=lnt@arizona.edu
#SBATCH --nodes=1
#SBATCH --ntasks=10
#SBATCH --mem=50gb
#SBATCH --time=10:00:00
#SBATCH --array=0-49

source ~/.bashrc && conda activate dfe-cnn
i=$SLURM_ARRAY_TASK_ID
printf -v j "%03d" $i # make j as i with 3 index

IN_DIR="data/dadi_test/all"
OUT_DIR="inference/all_snm_equil_3"
mkdir -p ${OUT_DIR}

dm_model="snm_1d"

model_sel="equil"
dfe_p0='0.5 1000'
dfe_lbounds='1e-4 1e-4'
dfe_ubounds='1 50000'

grids_cache="200 250 300"

dadi-cli InferDM --fs ${IN_DIR}/fs_${i}_syn --model ${dm_model} \
        --output-prefix ${OUT_DIR}/fs_${j} \
        --cpus 10 --force-convergence --nomisid
        
dadi-cli GenerateCache --model ${model_sel} \
        --demo-popt ${OUT_DIR}/fs_${j}.InferDM.simple.snm.txt \
        --output ${OUT_DIR}/fs_${j}.spectra.bpkl \
        --grids ${grids_cache} --sample-sizes 20 --cpus 10
    
dadi-cli InferDFE --fs ${IN_DIR}/fs_${i}_nonsyn \
        --cache1d ${OUT_DIR}/fs_${j}.spectra.bpkl \
        --demo-popt ${OUT_DIR}/fs_${j}.InferDM.simple.snm.txt \
        --output-prefix ${OUT_DIR}/fs_${j}.gamma \
        --pdf1d gamma --p0 ${dfe_p0} \
        --ubounds ${dfe_ubounds} --lbounds ${dfe_lbounds} \
        --ratio 2.31 --force-convergence --nomisid --cpus 10
    