name: dfe-cnn
channels:
  - conda-forge
dependencies:
  - pip
  - slim
  - tensorflow
  - scipy
  - numpy
  - matplotlib
  - ipykernel
  - dadi
  - multiprocess
  - stdpopsim
  - pip:
    - scikit-allel
