#!/bin/bash
#SBATCH --job-name=dadi_dfe_inference_two_epoch_rerun_not_converged
#SBATCH --output=outfiles/dadi_two_epoch/%x-%A_%a.out
#SBATCH --error=outfiles/dadi_two_epoch/%x-%A_%a.err
#SBATCH --account=rgutenk
#SBATCH --partition=high_priority
#SBATCH --qos=user_qos_rgutenk
#SBATCH --mail-type=ALL
#SBATCH --mail-user=lnt@arizona.edu
#SBATCH --nodes=1
#SBATCH --ntasks=10
#SBATCH --mem=50gb
#SBATCH --time=10:00:00
#SBATCH --array=2,4,8,10,11,14,15,18,27,28,29,30,31,32,33,36,37,41,43,44,46,47,48

source ~/.bashrc && conda activate dfe-cnn
i=$SLURM_ARRAY_TASK_ID
printf -v j "%03d" $i # make j as i with 3 index

IN_DIR="data/dadi_test/all"
OUT_DIR="inference/all_two_epoch"
mkdir -p ${OUT_DIR}

dfe_p0='0.5 1000'
dfe_lbounds='0 0'
dfe_ubounds='1 50000'

dadi-cli InferDFE --fs ${IN_DIR}/fs_${i}_nonsyn \
        --cache1d ${OUT_DIR}/fs_${j}.spectra.bpkl \
        --demo-popt ${OUT_DIR}/fs_${j}.InferDM.bestfits \
        --output-prefix ${OUT_DIR}/fs_${j}.gamma \
        --pdf1d gamma --p0 ${dfe_p0} \
        --ubounds ${dfe_ubounds} --lbounds ${dfe_lbounds} \
        --ratio 2.31 --force-convergence --nomisid --cpus 10 \
        --bestfit-p0-file ${OUT_DIR}/fs_${j}.gamma.InferDFE.bestfits